name: Run Tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  test:
    name: Run integration test using keria:${{ matrix.keria-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: signify-ts-test/
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        keria-version: ["0.2.0-dev3"]
        node-version: ["20"]
    env:
      KERIA_IMAGE_TAG: ${{ matrix.keria-version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}       
      - name: install deps
        run: |
          npm cache clean --force
          npm set registry https://registry.npmjs.org/
          npm ci     
      - name: Check formatting
        run: npm run pretty:check
      - name: Build
        run: npm run build
      - name: Print docker compose config
        run: docker compose config
      - name: docker compose down
        run: docker compose down;docker compose down
      - name: Start dependencies
        run: docker compose up proxy-verify -d --pull always
      - name: Run the vlei issuance test
        run: SIGNIFY_SECRETS="D_PbQb01zuzQgK-kDWjqy,BTaqgh1eeOjXO5iQJp6mb,Akv4TFoiYeHNqzj3N8gEg,CbII3tno87wn3uGBP12qm" TEST_ENVIRONMENT="docker" npx jest ./singlesig-vlei-issuance.test.ts
      - name: Run the generate reports test
        run: SIGNIFY_SECRETS="CbII3tno87wn3uGBP12qm" TEST_ENVIRONMENT="docker" npx jest ./report.test.ts
      - name: Run the vlei verification test
        run: SIGNIFY_SECRETS="CbII3tno87wn3uGBP12qm" TEST_ENVIRONMENT="docker" npx jest ./vlei-verification.test.ts
      - name: Run the proxy test
        run: SIGNIFY_SECRETS="CbII3tno87wn3uGBP12qm" TEST_ENVIRONMENT="docker" npx jest ./proxy-verify.test.ts

      # - name: Print logs
      #   run: docker compose logs
      #   if: always()
