name: Run Singlesig API Script Test
on:
  push:
    branches:
      - "main"
      - "fix_github_actions_refactor"
  pull_request:
    branches:
      - "main"
      - "fix_github_actions_refactor"
  workflow_dispatch:
jobs: 
  test-api-singlesig:
    name: Run single sig user integration test using keria:${{ matrix.keria-version }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    defaults:
      run:
        working-directory: signify-ts-test/
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        keria-version: ["0.2.0-dev3"]
        node-version: ["20"]
    env:
      KERIA_IMAGE_TAG: ${{ matrix.keria-version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: install deps
        run: |
          npm cache clean --force
          npm set registry https://registry.npmjs.org/
          npm ci    

      - name: Build
        run: npm run build

      - name: Issue Credentials, Generate reports, API test, Verifier test
        run: npx jest ./test/run-workflow-bank.test.ts --testNamePattern api-verifier-bank-test-workflow -- --bank-num "1" --max-report-size "0" --clean "false" --keria-start-port "3900"